version: "3.8"

services:
  personal-api:
    image: "sathyapm1006/22it046-personal-api"
    ports:
      - "5005:5000"  
    restart: always
  personal-api-2:
    image: "meghasreek25/22it020-personal-api"
    ports:
      - "5505:5000"  
    restart: always

  ml-model:
    image: "reenayasotha/ml-model:latest"  
    ports:
      - "6000:6000"  # Adjust if needed
    restart: alwaysUpdate this file to add the content
